# This script showcases how to use the function make_theo_scores to make theoretical scores from Grambank data, such as fusion, informativity etc.
# The script also compares the approach of Hedvigs/R_grambank_cookbook to that of grambank/grambank-analysed (release paper).
# In grambank/grambank-analysed we did a subsetting of the entire dataset where we pruned away features and languages with large amounts of missing data. We then used this subset in several parts of the analysis, including PCA and calculation of theoretical scores. The function make_theo_scores in R_scripts/make_theo_scores.R instead prunes for missing data with respect to the specific features involved in each of the theoretical scores. Furthermore, the function allows the users to set a different cut-off (default = 0.75). The difference is very small in practice, as will be evident by the plots generated by this script. Please see the following for more details: https://github.com/HedvigS/rgrambank?tab=readme-ov-file#theoretical-scores
# This example uses rcldf to fetch and parse Grambank v1.0.3 from Zenodo's online webplatform. If you already have Grambank downloaded locally, feel free to change the line which calls rcldf::cldf to point to the JSON-file instead. An example of this is provided below in a line that is commented out.
# This script specifies particular versions of the packages tidyverse and rcldf to increase replicability.

# written by Hedvig Skirgård 2024-04-25.


# the working directory should be set to R_grambank_cookbook/example_scripts, the location of this file.

#install.packages("devtools")
library(devtools)

#install_version("tidyverse", version = "2.0.0", repos = "http://cran.us.r-project.org")
library(tidyverse)

#install_github("SimonGreenhill/rcldf", dependencies = TRUE, ref = "v1.2.0")
library(rcldf)

#devtools::install_github("HedvigS/rgrambank", ref = "v1.0")
library(rgrambank)

if(!dir.exists("ouptut")){dir.create("output")}

# fetching Grambank v1.0.3 from Zenodo using rcldf (requires internet)
GB_rcldf_obj <- rcldf::cldf("https://zenodo.org/record/7844558/files/grambank/grambank-v1.0.3.zip", load_bib = F)

# fetching Grambank locally 
#GB_rcldf_obj <- rcldf::cldf("../../grambank/grambank/cldf/StructureDataset-metadata.json", load_bib = F)

# load_bib is set to FALSE because the bib-file is not necessary for these actions, and the package that rcldf dependes on for bibTeX parsin (bib2df) has some not-harmful but outdated code which generates warnings.

ValueTable <- rgrambank::make_binary_ValueTable(GB_rcldf_obj$tables$ValueTable)
ParameterTable <- rgrambank::make_binary_ParameterTable(GB_rcldf_obj$tables$ParameterTable)

theo_scores_table_cookbook <- rgrambank::make_theo_scores(ValueTable = ValueTable , 
                        ParameterTable =  ParameterTable)

theo_scores_table_cookbook %>% 
  write_tsv("output/Grambank_theo_scores.tsv", quote = "all")

#In order to compare to the grambank-analysed, we need the theo scores. I have copied the data over exactly as they are based on Grambank v1.0.3 and the following scripts:
#grambank-analysed/R_grambank/make_wide.R
#grambank-analysed/R_grambank/make_wide_binarized.R
#grambank-analysed/R_grambank/make_theo_score_fusion.R
#grambank-analysed/R_grambank/make_theo_scores.R

theo_scores_table_grambank_analysed <- readr::read_tsv("fixed/theo_scores.tsv", show_col_types = FALSE)

#renaming columns to differentiate the information
colnames(theo_scores_table_cookbook)[2:7] <- paste0(colnames(theo_scores_table_cookbook)[2:7], "_cookbook")

colnames(theo_scores_table_grambank_analysed)[2:7] <- paste0(colnames(theo_scores_table_grambank_analysed)[2:7], "_grambank-analysed")

joined <- inner_join(theo_scores_table_cookbook, theo_scores_table_grambank_analysed, by = join_by(Language_ID))

joined %>% 
  filter(!is.na(Fusion_cookbook)) %>% 
  filter(!is.na(`Fusion_grambank-analysed`)) %>% 
  ggplot(aes(x = Fusion_cookbook, y = `Fusion_grambank-analysed`)) +
  geom_point(color = "#FF689F") +
  theme_classic() +
  labs(x = "Fusion (Coookbook)", y = "Fusion (grambank-analysed)") +
  ggpubr::stat_cor(method = "pearson", p.digits = 2, geom = "label", color = "blue",
                   label.y.npc="top", label.x.npc = "left", alpha = 0.8) 

ggsave("output/theo_scores_table_cookbook_theo_scores_table_grambank_analysed_theo_score_fusion.png", height = 3, width = 3)

joined %>% 
  filter(!is.na(Informativity_cookbook)) %>% 
  filter(!is.na(`Informativity_grambank-analysed`)) %>%
  ggplot(mapping = aes(x = Informativity_cookbook, 
                       y = `Informativity_grambank-analysed`)) +
  geom_point(color = "steelblue2") +
  theme_classic() +
  labs(x = "Informativity (Coookbook)", y = "Informativity (grambank-analysed)") +
  ggpubr::stat_cor(method = "pearson", p.digits = 2, geom = "label", color = "blue",
                   label.y.npc="top", label.x.npc = "left", alpha = 0.8) 

ggsave("output/theo_scores_table_cookbook_theo_scores_table_grambank_analysed_theo_score_inform.png", height = 3, width = 3)